services:
  - type: web
    name: BharatPath-1
    env: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: AGMARKNET_API_KEY
        sync: false